# -*- coding: utf-8 -*-
"""Mini Game - Aventura no Castelo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKfvXne7Yr2qdgQCUnLsvf1T0sUpNbb8
"""

# Super Mario - Aventura no Castelo
# Projeto educativo com base nos principais conceitos de programação

# Variáveis iniciais
nome = "Mario"                      # String: nome do personagem
vidas = 3                           # Inteiro: número de vidas
moedas = 0                          # Inteiro: quantidade de moedas
tempo = 120.0                       # Float: tempo restante em segundos
esta_vivo = True                    # Booleano: verifica se o Mario ainda está no jogo
nivel = 1                           # Inteiro: fase atual

print(f"👨‍🔧 Bem-vindo, {nome}! Você tem {vidas} vidas e {tempo} segundos para salvar a princesa!\n")

# Loop do jogo (simulação simples com 3 desafios)
while esta_vivo and nivel <= 3:
    print(f"\n🌟 Nível {nivel} iniciado!")

    # Desafio: Mario coleta moedas
    moedas_coletadas = int(input("Quantas moedas Mario encontrou? "))
    moedas += moedas_coletadas

    # Tempo passa
    tempo -= 10.0

    # Evento aleatório (simulado): perdeu vida se moedas forem poucas
    if moedas_coletadas < 5:
        vidas -= 1
        print("💥 Mario tropeçou em um casco! Perdeu uma vida!")

    # Verifica se Mario ainda está vivo
    if vidas <= 0 or tempo <= 0:
        esta_vivo = False
        print("☠️ Mario perdeu todas as vidas ou ficou sem tempo!")
    else:
        print(f"✅ Fase {nivel} concluída! Mario agora tem {moedas} moedas e {vidas} vidas.")
        nivel += 1  # Vai para a próxima fase

# Final do jogo
print("\n🏁 Fim da Aventura!")

# Mensagem final com composição de strings
if esta_vivo:
    print(f"🎉 Parabéns, {nome}! Você salvou a princesa com {moedas} moedas restantes!")
else:
    print(f"😢 {nome}, você perdeu o jogo com {moedas} moedas acumuladas.")